### ISSUE TITLE
Ids out of sync

### ISSUE THREAD

**Issue by msdark** [rtfeldman/elm-css#128]
The resulting Html is not in sync with the names of the css ids.

`Style.elm`

      type CssIds
      = Container
      | Header

    navbarNamespace: Html.CssHelpers.Namespace String a b c
    navbarNamespace =
      withNamespace "navbar"

`View.elm`

     ...
    { id, class, classList } = navbarNamespace
    navbar : Html a
    navbar =
       header [id Header] []

The results is 
`<header id="Header"></header>` instead of `<header id="navbarHeader"></header>`

I'm running Elm 0.17 with elm-css from this repository instead of the npm package (because of #125) (and using https://github.com/msdark/elm-css-webpack-loader/tree/upgrade-v0.17)

An example https://github.com/msdark/elm-css-test

**Comment by stkb** [comment]
Yeah I noticed this too while trying the example in this repo, where the styles referenced by IDs don't get applied because of this reason. It looks like #115 was a fix to this and I don't know why but that was closed without comment.

**Comment by msdark** [comment]
@rtfeldman any idea ?

**Comment by rtfeldman** [comment]
I closed #115 without comment because it didn't make sense to me, and since the author put only a microscopic sliver of effort into clarifying intent, I decided against wasting more time on it. 😉 

However, it looks like #115 was correct. (I honestly didn't notice because I never use IDs for styling, but since IDs are supposed to be globally unique, makes sense not to namespace them.)

Published fix as 3.1.0, along with some minor additions.

@msdark I can no longer reproduce on your example repo. Thanks for reporting, and please close if this is resolved for you!

**Comment by gigathlete** [comment]
Thank you.
