### ISSUE TITLE
Possible to leverage elm-html?

### ISSUE THREAD

**Issue by kevinSuttle** [rtfeldman/elm-css#157]
Looking at the duplication here: https://github.com/rtfeldman/elm-css/blob/master/src/Css/Elements.elm#L1

I'm wondering if it's possible in Elm to use that same list of HTML Elements without having to re-declare them. I understand that they're different functions. Just curious more than anything.

**Comment by tolgap** [comment]
This is not possible because in `elm-html` the elements are defined as:

```elm
div : List (Attribute msg) -> List (Html msg) -> Html msg
```

Which does not fit in with how we use them at `elm-css`:

```elm
div
    [ mixin1
    , mixin2
 -- , etc...
    ]
```

Where the type of `div` being

```elm
div : List Mixin -> Snippet
```

The best part is, you don't have to use `elm-html` as your renderer. `elm-css` is agnostic. If you check `elm-package.json`, you'll see that `elm-html` is not a dependency 👍 .

An example: You can also render your CSS to a list of tuples using `Css.asPairs`.

```elm
asPairs : List Mixin -> List ( String, String )
```

**Comment by kevinSuttle** [comment]
Ah ok. Good to know!
