### ISSUE TITLE
README logo is not scaled in the elm packages page

### ISSUE THREAD

**Issue by AntouanK** [rtfeldman/elm-css#283]
Just noticed that the logo from the `README.md` file is not scaled properly in the elm packages page.

<img width="1188" alt="screen shot 2017-06-28 at 07 16 36" src="https://user-images.githubusercontent.com/4569111/27651153-908ddd96-5c37-11e7-816e-6e9c0dc7b9b0.png">

**Comment by BobWhitelock** [comment]
I investigated this a little bit, and came to the conclusion this is more an issue with package.elm-lang.org than elm-css itself. While it may be possible to work around it by linking a low resolution version of the logo, I think it would be better to fix this at the root cause. See https://github.com/elm-lang/package.elm-lang.org/issues/238 for more details.

**Comment by akoppela** [comment]
PR for that https://github.com/elm-lang/package.elm-lang.org/pull/242

**Comment by BobWhitelock** [comment]
@akoppela: nice!

**Comment by rtfeldman** [comment]
Manually fixed - thanks!
