### ISSUE TITLE
Deprecate `asPairs`

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/elm-css#302]
Currently `elm-css` can be used in one of three ways:

1. Compile to a `.css` file
2. Compile to a string and use a `<style>` element
3. Compile to key/value pairs with [`asPairs`](http://package.elm-lang.org/packages/rtfeldman/elm-css/9.1.0/Css#asPairs) and create a [`style`](http://package.elm-lang.org/packages/elm-lang/html/2.0.0/Html-Attributes#style) attribute

I think supporting the third one no longer makes sense, and [`asPairs`](http://package.elm-lang.org/packages/rtfeldman/elm-css/9.1.0/Css#asPairs) should be deprecated.

The benchmarks I've seen - some of which are linked in https://github.com/elm-lang/virtual-dom/issues/112 - make it pretty clear that the `style` attribute is a slow choice for general styling, which is one reason the major CSS frameworks in the JS ecosystem have moved away from it.

On top of this, there have always been issues with this approach. `hover` will compile to `asPairs` just fine, but it won't actually work when you run it because `<style>` supports pseudo-classes but the `style` attribute doesn't. Also, `style` attributes have their own elevated level of specificity, so they don't play nicely with any other sources of styles you might want to incorporate - resets, polyfills, Bootstrap, etc.

I think there are good reasons to support both compiling to a `.css` file and generating styles at runtime, but I want `elm-css` to offer only two options: either use a `<style>` element, or use the CLI to generate a `.css` file.

**Comment by therealnicksaunders** [comment]
First off, @rtfeldman, thanks for your great work on this library, and I appreciate that you are putting this issue up for community input.

One thing I don't want to lose is the ability to maintain my styles alongside the corresponding view code because I would typically be tweaking these at the same time. To me, that's the big downside of having an external stylesheet.

Some component-oriented frameworks like Angular and [Svelte](http://github.com/sveltejs/svelte) allow you to author a stylesheet in the context of a component. Then, at runtime, they add a scoped version of the stylesheet to the document head. So, your styles are still programmatically bound to the corresponding view (to some extent anyway), but they have the flexibility and performance of a stylesheet that you described.

I'm a total Elm newbie, but so far my understanding is that, for better or for worse, we can't touch the document head except maybe through ports. But if we could, I think it would be nice to have elm-css (elm-css-helpers?) provide a function along the lines of...

```
stylesheet : List Style -> Html.Attribute
```

...where a stylesheet is generated from the ```List Style``` and added to the document and can be linked to the corresponding element by including the returned attribute.

Clearly this example is oversimplified (ignores the side-effect of adding the stylesheet, for example), but is something like this even a remote possibility?

**Comment by therealnicksaunders** [comment]
By the way, after thinking about it for five more minutes, the function above wouldn't even have to return an attribute--it could just return a generated class name in order to avoid that elm-lang/html dependency.

**Comment by rtfeldman** [comment]
@therealnicksaunders take a look at https://github.com/elm-lang/virtual-dom/issues/112 - I'm generally in agreement that this is the right way to do things instead of `asPairs`, and that's basically where I'm aiming to end up. 😄

**Comment by sporto** [comment]
I have used `asPairs` several times when I don't want to take the time to wire all the things needed for proper style tags. I think `asPairs` is quite handy in some cases as is easy to use. I think it should stay until using <style> is almost painless. Which I don't think it is now (I need to collect styles, create a style node, etc)

**Comment by kuon** [comment]
I am also using `asPairs` for my styling. I found it was much easier to maintain style within view code. Organizing views is hard enough without having to duplicate everything for styling.

One of the reason `elm-css` is great, is because I can mix my styling with my view code.

Also dynamic styling, for example:

```elm
styles : List Css.Style -> Html.Attribute msg
styles =
  Css.asPairs >> Html.Attributes.style

logo : Int -> Html msg
logo size =
  div [ styles [
          fontSize (px (floor <| size * 0.6))
          , height (px size)
          , width (px size)
          ]][]
```

**Comment by rtfeldman** [comment]
@kuon I did a mockup of some documentation for what I'm currently planning - based on your description, you may like this even better. 😄  https://gist.github.com/rtfeldman/7665f28270352521163f9ec2ee772ec1

Thoughts?

**Comment by kuon** [comment]
@rtfeldman I really like both approach. The new `uniqueClass` helper would solve one part of the problem I have, and the new "inline style" with `Html.Styled` would solve another part (dynamic styles). Do you plan to allow them to be used together? Because in my use case, `uniqueClass` static css would be like 95% of my css, the last 5% being dynamic.

**Comment by rtfeldman** [comment]
Personally I'd choose one or the other, but I can't think of a reason that wouldn't work!

I'm curious - why not just go 100% dynamic and remove the build step?

**Comment by kuon** [comment]
Mostly because of PostCSS (I use autoprefixer), and also things like keyframes/mediaQueries/pseudo elements.

**Comment by rtfeldman** [comment]
Ah gotcha! PostCSS makes sense 👍 

Media Queries and pseudo-elements still work exactly the same way in the dynamic version (maybe I should emphasize that in the docs?) and keyframes will too once https://github.com/rtfeldman/elm-css/issues/313 is implemented. 😄

**Comment by kuon** [comment]
Yeah it's really not clear how to use mediaQueries and pseudo-elements.

But autoprefixer is still absolutely required for many things, things like `user-select` or `transform` still need a prefix in many modern browsers.

**Comment by rtfeldman** [comment]
Deprecated in favor of #327
