### ISSUE TITLE
Rename the css function to "styles"?

### ISSUE THREAD

**Issue by edkv** [rtfeldman/elm-css#343]
I don't have any strong arguments about this but it just feels nicer to me :)

```elm
myButton : Html msg
myButton =
    button [ styles myButtonStyles, onClick DoSomething ]
        [ text "Click me!"
        ]
```

And we can also rename the `style` attribute to `inlineStyles`. This will make the difference between them clearer.

**Comment by rtfeldman** [comment]
I thought about this at first, but I've often found myself writing functions that take an argument called `styles` which is a `List Style`, and it would be annoying to have that shadow the same function.

I also like how this is farther away from `style`, so if there are any places where you're still using `style` instead of `css`, they stand out!

> And we can also rename the `style` attribute to `inlineStyles`. This will make the difference between them clearer.

It's important to me that `Html.Styled` and friends not make changes to the original APIs. I really want it to be a drop-in replacement!

**Comment by edkv** [comment]
>I've often found myself writing functions that take an argument called styles

Well, it is probably always possible to rename it to something like `buttonStyles` instead.

>I really want it to be a drop-in replacement!

>I also like how this is farther away from style

Ok, this makes sense!
