### ISSUE TITLE
WebExtensions modifying CSS breaks DOM changes

### ISSUE THREAD

**Issue by aidalgol** [rtfeldman/elm-css#473]
I use a WebExtension that applies a dark colour-theme to pages, and this seems to completely break elm-css.  I have an app that is a variant of the [inc/dec example in the Elm guides](https://github.com/evancz/elm-architecture-tutorial/blob/master/examples/01-button.elm) with styling applied with elm-css, and when I clicked either button (of the inc/dec buttons), a flood of `domNode is undefined` appeared in the console.

I have had layout breakage occur from my user-applied styles, but I have never had it cause JS errors, so I don't think this browser add-on is doing anything wrong, and this has exposed a bug in elm-css or Elm itself.

**Comment by rtfeldman** [comment]
This is a tricky situation!

Here are some things that are true:

* Elm renders a working web page
* When you turn on that browser extension, that formerly working page no longer works
* The resulting error comes from the Elm runtime, so it appears to be "Elm's fault" even though Elm delivered a perfectly working page before the extension broke it!

It's conceivable that Elm could change how its rendering system works, to accommodate the browser extension. However, doing that can result in performance degradation for everyone who's not using the extension. Is that the right tradeoff for Elm to make?

Like I said, it's tricky!

At any rate, this is not something `elm-css` has any ability to affect. Any change that could possibly affect these symptoms would have have to come from one of two places:

1. The browser extension
2. Elm's virtual DOM

If you'd like to open an issue on the vdom system, here is a link to its issue tracker: https://github.com/elm/virtual-dom/issues

Hope that helps! Since there aren't any possible relevant `elm-css` changes here, I'm going to close this issue.

**Comment by aidalgol** [comment]
Thank you very much for the detailed response.  I had a suspicion that this may be out of scope of `elm-css`, but decided to report it here since the problem went away when I removed my use of `elm-css`.  I agree that there is no obvious right answer to how to resolve this clash.

Just now, I was about to open a ticket on the extension, but this appears to be a known issue and not just with Elm: darkreader/darkreader#623.  One of this extension's modes of operations is essentially an injection hack, so it's no wonder it breaks Virtual DOM implementations.  My apologies for not searching there before creating this issue.

**Comment by rtfeldman** [comment]
No worries! Thanks for posting. ♥️
