### ISSUE TITLE
Add a `color : Color.Color` field to `Css.Color`

### ISSUE THREAD

**Issue by mdgriffith** [rtfeldman/elm-css#76]
I'm starting a package for [color mixing functions in elm](https://github.com/mdgriffith/elm-color-mixing). 

My plan is to cover all color functions that are documented in the LessCss preprocessor:

[http://lesscss.org/functions/#color-operations](http://lesscss.org/functions/#color-operations)

And to use the [Core Color type](http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Color) provided by Elm.

I definitely want to make sure it's compatible with elm-css, though with the current plan I believe that means elm-css would have to switch over to using the core Color type.  I don't know if there are any issues with that though.

Anyway, let me know your thoughts!
I'm going to be starting work pretty quick.

**Comment by rtfeldman** [comment]
This should be pretty straightforward.

We just need to add a `color : Color.Color` field such that you can ultimately do this in elm-repl:

```elm
> (Css.rgb 22 23 24).color
RGBA 22 23 24 1 : Color.Color
```

**Comment by mdgriffith** [comment]
Just fyi, I finished the initial version of the color mixing library:
http://package.elm-lang.org/packages/mdgriffith/elm-color-mixing/1.0.2/

**Comment by rtfeldman** [comment]
Awesome! :tada:

**Comment by chaughawout** [comment]
I'll take a stab at this over the next few days.

**Comment by chaughawout** [comment]
So here's what I have after a couple hours of tinker arounding:
```elm
mapColor : (Color.Color -> Color.Color) -> Color -> Color
mapColor mapper cssColor =
    let
        { red, green, blue, alpha } =
            Color.toRgb << mapper
    in
        { cssColor | colorValue = Compatible, red = red, green = green, blue = blue, alpha = alpha }
```

This doesn't work because mapper needs an additional argument. I'm relatively new to Elm, but I think this fits the general idea of the mapColor function, but I'm missing something crucial. If anyone can point out what I'm doing wrong here, that would be really helpful.

Also, this issue is really old and I noticed the #167 was closed already. Is this issue relevant still?

**Comment by kuon** [comment]
Any update on this? Color manipulation is the thing missing from elm-css to use it over sass.

**Comment by rtfeldman** [comment]
I started work on something similar on a branch...no ETA yet though. 🙂

**Comment by kuon** [comment]
If I can help in anyway, tell me.

**Comment by kuon** [comment]
Btw, if anybody wants to chime into https://github.com/mdgriffith/elm-color-mixing/issues/3 for the preferred syntax.

**Comment by mthadley** [comment]
Just out of curiosity, what is the status of this now? 

I recently was converting over some Sass styles to `elm-css` and realized that I didn't have a way of translating over the color mixing that I had.

**Comment by mikolajpp** [comment]
This feature would be very useful: currently I need to keep duplicate 
colors for style-elements and Css which I use to style foreign app.

**Comment by rtfeldman** [comment]
Unfortunately this won't work out anymore based on the new "do everything at runtime" strategy. For performance reasons we'll be compiling directly to strings rather than keeping runtime metadata around like colors. So accessing the colors would require something like parsing the compiled CSS string, which doesn't sound like a good idea.
