### ISSUE TITLE
Vendor prefixes?

### ISSUE THREAD

**Issue by kittykatattack** [rtfeldman/elm-css#79]
Hello! 

This is a feature request for automatic vendor-prefixes for the "experimental" CSS properties.

Thanks!

**Comment by tcoopman** [comment]
Wouldn't this be easier as a post processing step?
I've been thinking about doing a webpack loader for elm-css (see #74) and then you could just chain it with https://github.com/postcss/autoprefixer#webpack to get the vendor prefixes.
Of course you could do a similar thing with other tools.

**Comment by lukewestby** [comment]
I agree with @tcoopman, things that can be done once you have a complete CSS file are better handled by another tool like PostCSS. Better to keep the scope of this tool focused :smile:

**Comment by kittykatattack** [comment]
I would prefer to have an all-in-one tool rather than to add an additional processing step.

**Comment by tcoopman** [comment]
@kittykatattack I can see why you would want that, but for me personally (from a user perspective), I would love for the maintainers to only focus on making elm-css as good as possible without having to worry about things like vender-prefixes.
It seems that css is already hard enough without having to worry about vendor-prefixes.

For me the extra step of for example using PostCSS (with a plugin that's completely focused on prefixes) is totally ok! The PostCSS plugin will probably do vendor-prefixes better because it's focused on that. So why not use that tool?

**Comment by rtfeldman** [comment]
Good news: I agree with everyone in this thread! :smile_cat: 

I recently went over how the elm-css internals work with @evancz and @eeue56, and  the result is that now elm-css supports lightweight *stylesheet transformations* that mean it is now something like Sass plus PostCSS in a tasty Elm wrapper. :yum: 

For example, I extracted the namespace functionality into a transformation: https://github.com/rtfeldman/elm-css/blob/master/src/Css/Namespace.elm

So now instead of saying `stylesheet { namespace = "test" }` you can either call `stylesheet` to ignore the namespace feature, or [`(stylesheet << namespace "test")`](https://github.com/rtfeldman/elm-css/blob/master/test/Properties.elm#L365) to use it. It's optional, but super easy to drop in; you don't need a heavyweight post-processing pipeline to do this.

In the same vein, anyone can now implement something like [autoprefixer](https://github.com/postcss/autoprefixer) as one of these transformations, at which point enabling it would be as trivial as writing `(stylesheet << autoprefix)` instead of `stylesheet`.

I realize I haven't documented this feature, but I definitely intend to now that it works! :smile:

**Comment by rtfeldman** [comment]
(Having said that, if you don't want to wait for someone to implement some sort of automatic prefixing solution for elm-css, I also agree that using PostCSS right now is totally rad.)

**Comment by kittykatattack** [comment]
@rtfeldman Thank you so much, Richard! :sparkling_heart: 
I actually think these built-in features are extremely important.
One of main reasons I'm using Elm is to escape JavaScript Toolchain Dependency Hell and the Build-Management Death Spiral.
I love the fact that I can run `elm make` and its suddenly all just Lotus Petals and Kittens :smile:

**Comment by lukewestby** [comment]
@kittykatattack already underway in light of this news :smile:

https://github.com/lukewestby/elm-css-autoprefix

**Comment by kittykatattack** [comment]
Utopia!!

**Comment by lukewestby** [comment]
@rtfeldman can this be closed?

**Comment by rtfeldman** [comment]
Yep!
